ci: fix bu

diff --git a/.github/workflows/preview.yml b/.github/workflows/preview.yml
--- a/.github/workflows/preview.yml
+++ b/.github/workflows/preview.yml
@@ -47,8 +47,13 @@ jobs:
             - name: Deploy
               id: deploy
               run: |
-                  HAS_BEEN_DEPLOYED=$(flyctl status --app "${{ env.APP_NAME }}" --json | jq -r .Deployed)
-                  flyctl deploy --app "${{ env.APP_NAME }}" --now --remote-only --strategy immediate || ([ "$HAS_BEEN_DEPLOYED" != "true" ] && sleep 15)
+                  exec 5>&1
+                  DEPLOY_LOG=$((flyctl deploy --app "${{ env.APP_NAME }}" --now --remote-only --strategy immediate && echo '✅ DEPLOY SUCCESSFUL, following up with status checks... (#EC1)' || echo '❌ DEPLOY FAILED; Might be misleading error, checking... (#EC2)') | tee >(cat - >&5))
+                  if tail "$DEPLOY_LOG" | grep -F '#EC2'; then
+                    if tail -n 20 "$DEPLOY_LOG" | grep -F 'No deployment available to monitor'; then
+                        sleep 15
+                    else; exit 1; fi
+                  fi
                   flyctl status --app "${{ env.APP_NAME }}"
                   APP_STATUS=$(flyctl status --app "${{ env.APP_NAME }}" --json)
                   APP_HOSTNAME=$(printf '%s' "$APP_STATUS" | jq -r .Hostname)
