ci: fix deploys (#246)

diff --git a/.github/workflows/preview.yml b/.github/workflows/preview.yml
--- a/.github/workflows/preview.yml
+++ b/.github/workflows/preview.yml
@@ -48,11 +48,15 @@ jobs:
               id: deploy
               run: |
                   exec 5>&1
-                  DEPLOY_LOG=$((flyctl deploy --app "${{ env.APP_NAME }}" --now --remote-only --strategy immediate && echo '✅ DEPLOY SUCCESSFUL, following up with status checks... (#EC1)' || echo '❌ DEPLOY FAILED; Might be misleading error, checking... (#EC2)') | tee >(cat - >&5))
-                  if tail "$DEPLOY_LOG" | grep -F '#EC2'; then
-                    if tail -n 20 "$DEPLOY_LOG" | grep -F 'No deployment available to monitor'; then
+                  DEPLOY_LOG=$((flyctl deploy --app "${{ env.APP_NAME }}" --now --remote-only --strategy immediate 2>&1 && echo '✅ DEPLOY SUCCESSFUL, following up with status checks... (#EC1)' || echo '❌ DEPLOY FAILED; Might be misleading error, checking... (#EC2)') | tee >(cat - >&5))
+                  if echo "$DEPLOY_LOG" | grep -F '#EC2'; then
+                    if echo "$DEPLOY_LOG" | grep -F 'No deployment available to monitor'; then
+                        echo "🐛 Known bug, continuing..."
                         sleep 15
-                    else exit 1; fi
+                    else
+                        echo "🚨 The deployment failed. Check the logs above."
+                        exit 1
+                    fi
                   fi
                   flyctl status --app "${{ env.APP_NAME }}"
                   APP_STATUS=$(flyctl status --app "${{ env.APP_NAME }}" --json)
